DichVuGame/Models/Studio.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace DichVuGame.Models
{
    public class Studio
    {
        public int ID { get; set; }
        [Display(Name = "Tên Studio")]
        public string Studioname { get; set; }
        [Display(Name = "Logo Studio")]
        public string StudioLogo { get; set; }
        [Display(Name = "Mô tả")]
        public string Describe { get; set; }
        [Display(Name = "Quốc gia")]
        public int CountryID { get; set; }
        public Country Country { get; set; }
        public virtual ICollection<Game> Games { get; set; }
    }
}

DichVuGame/Areas/Admin/Controllers/StudiosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DichVuGame.Data;
using DichVuGame.Models;
using Microsoft.Extensions.Hosting.Internal;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using DichVuGame.Utility;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace DichVuGame.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class StudiosController : Controller
    {
        private readonly ApplicationDbContext _context;
        public IWebHostEnvironment _hostEnvironment;
        public StudiosController(ApplicationDbContext context,IWebHostEnvironment hostingEnvironment)
        {
            _context = context;
            _hostEnvironment = hostingEnvironment;
        }

        // GET: Admin/Studios
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Studios.Include(s => s.Country);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Admin/Studios/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var studio = await _context.Studios
                .Include(s => s.Country)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (studio == null)
            {
                return NotFound();
            }

            return View(studio);
        }

        // GET: Admin/Studios/Create
        public IActionResult Create()
        {
            ViewData["CountryID"] = new SelectList(_context.Countries, "ID", "Countryname");
            return View();
        }

        // POST: Admin/Studios/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Studioname,StudioLogo,Describe,CountryID")] Studio studio)
        {
            if (ModelState.IsValid)
            {
                _context.Add(studio);
                await _context.SaveChangesAsync();
                var webRootPath = _hostEnvironment.WebRootPath;
                var files = HttpContext.Request.Form.Files;
                if(files.Count > 0)
                {
                    var path = Path.Combine(webRootPath, SD.StudioImageFolder);
                    var extension = Path.GetExtension(files[0].FileName);
                    using (var fileStream = new FileStream(Path.Combine(path, studio.ID + extension), FileMode.Create))
                    {
                        files[0].CopyTo(fileStream);
                    }
                    studio.StudioLogo = @"\" + SD.StudioImageFolder + @"\" + studio.ID + extension;
                }
                else
                {
                    var path = Path.Combine(webRootPath, SD.DefaultStudioImage);
                    System.IO.File.Copy(path,webRootPath + @"\" + SD.StudioImageFolder + @"\" + studio.ID + ".jpeg");
                    studio.StudioLogo = @"\" + SD.StudioImageFolder + @"\" + studio.ID + ".jpeg";
                }
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CountryID"] = new SelectList(_context.Countries, "ID", "ID", studio.CountryID);
            return View(studio);
        }

        // GET: Admin/Studios/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var studio = await _context.Studios.FindAsync(id);
            if (studio == null)
            {
                return NotFound();
            }
            ViewData["CountryID"] = new SelectList(_context.Countries, "ID", "ID", studio.CountryID);
            return View(studio);
        }

        // POST: Admin/Studios/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Studioname,StudioLogo,Describe,CountryID")] Studio studio)
        {
            if (id != studio.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(studio);
                    await _context.SaveChangesAsync();
                    var webRootPath = _hostEnvironment.WebRootPath;
                    var files = HttpContext.Request.Form.Files;
                    if(files.Count > 0)
                    {
                        if(studio.StudioLogo != null)
                        {
                            var old = webRootPath + @"" + studio.StudioLogo;
                            System.IO.File.Delete(old);
                        }
                        var path = Path.Combine(webRootPath, SD.StudioImageFolder);
                        var extension = Path.GetExtension(files[0].FileName);
                        using(var fileStream = new FileStream(Path.Combine(path,studio.ID + extension),FileMode.Create))
                        {
                            files[0].CopyTo(fileStream);
                        }
                        studio.StudioLogo = @"\" + SD.StudioImageFolder + @"\" + studio.ID + extension;
                    }
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StudioExists(studio.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CountryID"] = new SelectList(_context.Countries, "ID", "ID", studio.CountryID);
            return View(studio);
        }

        // GET: Admin/Studios/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var studio = await _context.Studios
                .Include(s => s.Country)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (studio == null)
            {
                return NotFound();
            }

            return View(studio);
        }

        // POST: Admin/Studios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var studio = await _context.Studios.FindAsync(id);
            System.IO.File.Delete(_hostEnvironment.WebRootPath + @"\" + studio.StudioLogo);
            _context.Studios.Remove(studio);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool StudioExists(int id)
        {
            return _context.Studios.Any(e => e.ID == id);
        }
    }
}

DichVuGame/Areas/Admin/Views/Studios/Create.cshtml
@model DichVuGame.Models.Studio

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Studio</h4>
<hr />
<div class="p-4 border rounded">
    <form asp-action="Create" enctype="multipart/form-data">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="Studioname" class="control-label"></label>
            </div>
            <div class="col-6">
                <input asp-for="Studioname" class="form-control" />
                <span asp-validation-for="Studioname" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="StudioLogo" class="control-label"></label>
            </div>
            <div class="col-6">
                <input type="file" name="files" />
            </div>
        </div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="Describe" class="control-label"></label>
            </div>
            <div class="col-6">
                <input asp-for="Describe" class="form-control" />
                <span asp-validation-for="Describe" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="CountryID" class="control-label"></label>
            </div>
            <div class="col-6">
                <select asp-for="CountryID" class="form-control" asp-items="ViewBag.CountryID"></select>
            </div>
        </div>
        <div class="form-group">
            <input type="submit" value="Create" class="btn btn-primary" />
        </div>
    </form>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>

DichVuGame/Areas/Admin/Views/Studios/Delete.cshtml
@model DichVuGame.Models.Studio

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Studio</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Studioname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Studioname)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Describe)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Describe)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Country)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Country.ID)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

DichVuGame/Areas/Admin/Views/Studios/Details.cshtml
@model DichVuGame.Models.Studio

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div class="p-4 border rounded">
    <h4>Studio</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Studioname)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Studioname)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.StudioLogo)
        </dt>
        <dd class="col-sm-10">
            <img src="@Model.StudioLogo" width="150" height="150"/>
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Describe)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Describe)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Country)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Country.ID)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

DichVuGame/Areas/Admin/Views/Studios/Edit.cshtml
@model DichVuGame.Models.Studio

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Studio</h4>
<hr />

<form asp-action="Edit">
    <div class="p-4 border rounded">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="ID" />
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="Studioname" class="control-label"></label>
            </div>
            <div class="col-6">
                <input asp-for="Studioname" class="form-control" />
                <span asp-validation-for="Studioname" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="StudioLogo" class="control-label"></label>
            </div>
            <div class="col-6">
                <input name="files" type="file"/>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="Describe" class="control-label"></label>
            </div>
            <div class="col-6">
                <input asp-for="Describe" class="form-control" />
                <span asp-validation-for="Describe" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="CountryID" class="control-label"></label>
            </div>
            <div class="col-6">
                <select asp-for="CountryID" class="form-control" asp-items="ViewBag.CountryID"></select>
                <span asp-validation-for="CountryID" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <input type="submit" value="Lưu" class="btn btn-primary" />
        </div>
    </div>
</form>


<div>
    <a asp-action="Index">Quay lại</a>
</div>

DichVuGame/Areas/Admin/Views/Studios/Index.cshtml
@model IEnumerable<DichVuGame.Models.Studio>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Studioname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StudioLogo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Describe)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Country)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Studioname)
            </td>
            <td>
                <img src="@item.StudioLogo" width="150" height="150" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Describe)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Country.ID)
            </td>
            <td>
                <a type="button" class="btn btn-success" asp-action="Edit" asp-controller="Studios" asp-route-id="@item.ID"><i class="fas fa-edit"></i></a>
                <a type="button" class="btn btn-info" asp-action="Details" asp-controller="Studios" asp-route-id="@item.ID"><i class="far fa-list-alt"></i></a>
                <a type="button" class="btn btn-danger" asp-action="Delete" asp-controller="Studios" asp-route-id="@item.ID"><i class="fas fa-trash-alt"></i></a>
            </td>
        </tr>
}
    </tbody>
</table>